version: '3.8'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .denv
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5151:5432"

  backend:
    build:
      context: ./app  # Adjusted to the correct relative path
      dockerfile: Dockerfile  # Specified the correct Dockerfile for the backend
    ports:
      - "3000:3000"  # Adjusted to match the EXPOSE in Dockerfile-1
    depends_on:
      - postgres
    env_file:
      - .denv  # Path to your .env file

  # frontend:
  #   build:
  #     context: ./src  # Adjusted to the correct relative path
  #     dockerfile: Dockerfile  # Specified the correct Dockerfile for the frontend
  #   ports:
  #     - "5500:5500"  # Adjusted to match the EXPOSE in the frontend Dockerfile